---
include:
  # Components from the CI/CD Catalog: https://gitlab.group.one/explore/catalog
  # Build, security scan, and release the docker image: https://gitlab.group.one/explore/catalog/ci/docker
  - component: ${CI_SERVER_HOST}/ci/docker/build@main
    inputs:
      image_name: wp-in/wordpress-task-sizer

stages:
  - build
  - release

.deploy-template:
  image: harbor.one.com/standard-images/ci/kubectl:jammy-rootless
  tags:
    - k8s-small
  stage: release
  dependencies: [ build-image ]
  script:
    - kubectl-setup
    - ./kubernetes/generate-yaml.sh | tee tmp-deployment.yaml
    - kubectl apply --dry-run=server --validate --filename tmp-deployment.yaml
    - kubectl apply --validate --filename tmp-deployment.yaml
  after_script:
    # wait for rollout to be complete
    - kubectl -n devin-dashboard rollout status deployment.apps/wordpress-task-sizer-backend-$RELEASE_ENVIRONMENT

deploy-production:
  extends: .deploy-template
  variables:
    RELEASE_ENVIRONMENT: production
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+(\.\d+)?-production$/'
      when: manual
  environment:
    name: k8spod2

